POST http://localhost:7071/api/la-stateful-x12tocsv/triggers/manual/invoke?api-version=2020-05-01-preview&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=MAA_o3ghspSRoT8XJiSzOYILxEWxrlXEn7asFEKcuKQ HTTP/1.1
Content-Type:application/json

[
   {
      "ns0:X12_00501_837_P":{
         "@xmlns:ns0":"http://schemas.microsoft.com/BizTalk/EDI/X12/2006",
         "ST":{
            "ST01":"837",
            "ST02":"72278993",
            "ST03":"005010X222A1"
         },
         "ns0:BHT":{
            "BHT01":"0019",
            "BHT02":"00",
            "BHT03":"72278993",
            "BHT04":"20211022",
            "BHT05":"200438",
            "BHT06":"CH"
         },
         "ns0:NM1Loop1":[
            {
               "ns0:NM1":{
                  "NM101":"41",
                  "NM102":"2",
                  "NM103":"999999",
                  "NM108":"46",
                  "NM109":"999999"
               },
               "ns0:PER":{
                  "PER01":"IC",
                  "PER03":"TE",
                  "PER04":"9999999999"
               }
            },
            {
               "ns0:NM1":{
                  "NM101":"40",
                  "NM102":"2",
                  "NM103":"COMPANYNAMEHERE",
                  "NM108":"46",
                  "NM109":"123456789"
               }
            }
         ],
         "ns0:HLLoop1":[
            {
               "ns0:HL":{
                  "HL01":"1",
                  "HL03":"20",
                  "HL04":"1"
               },
               "ns0:PRV":{
                  "PRV01":"BI",
                  "PRV02":"PXC",
                  "PRV03":"282N00000X"
               },
               "ns0:NM1Loop2":[
                  {
                     "ns0:NM1_2":{
                        "NM101":"85",
                        "NM102":"2",
                        "NM103":"SOUTHERN VIRGINIA REGIONAL MEDICAL C",
                        "NM108":"XX",
                        "NM109":"1104461276"
                     },
                     "ns0:N3_2":{
                        "N301":"727 N MAIN ST"
                     },
                     "ns0:N4_2":{
                        "N401":"EMPORIA",
                        "N402":"VA",
                        "N403":"238471274"
                     },
                     "ns0:REF_3":{
                        "REF01":"EI",
                        "REF02":"843065045"
                     },
                     "ns0:PER_2":{
                        "PER01":"IC",
                        "PER02":"ABC DEF",
                        "PER03":"TE",
                        "PER04":"1234567890"
                     }
                  },
                  {
                     "ns0:NM1_2":{
                        "NM101":"87",
                        "NM102":"2"
                     },
                     "ns0:N3_2":{
                        "N301":"PO BOX 639858"
                     },
                     "ns0:N4_2":{
                        "N401":"CINCINNATI",
                        "N402":"OH",
                        "N403":"452639858"
                     }
                  }
               ]
            },
            {
               "ns0:HL":{
                  "HL01":"2",
                  "HL02":"1",
                  "HL03":"22",
                  "HL04":"0"
               },
               "ns0:SBR":{
                  "SBR01":"P",
                  "SBR02":"18",
                  "SBR03":"123451MA02",
                  "SBR09":"BL"
               },
               "ns0:NM1Loop2":[
                  {
                     "ns0:NM1_2":{
                        "NM101":"IL",
                        "NM102":"1",
                        "NM103":"JOHN",
                        "NM104":"SMITH",
                        "NM108":"MI",
                        "NM109":"FV1234567890"
                     },
                     "ns0:N3_2":{
                        "N301":"PO BOX 123"
                     },
                     "ns0:N4_2":{
                        "N401":"LAWRENCEVILLE",
                        "N402":"VA",
                        "N403":"23868"
                     },
                     "ns0:DMG":{
                        "DMG01":"D8",
                        "DMG02":"19900820",
                        "DMG03":"M"
                     },
                     "ns0:REF_3":{
                        "REF01":"SY",
                        "REF02":"123456789"
                     }
                  },
                  {
                     "ns0:NM1_2":{
                        "NM101":"PR",
                        "NM102":"2",
                        "NM103":"VA BLUE CROSS OF VIRGINIA PPO",
                        "NM108":"PI",
                        "NM109":"999990070"
                     },
                     "ns0:N3_2":{
                        "N301":"P O BOX 27401"
                     },
                     "ns0:N4_2":{
                        "N401":"RICHMOND",
                        "N402":"VA",
                        "N403":"23279"
                     }
                  }
               ],
               "ns0:CLMLoop1":{
                  "ns0:CLM":{
                     "CLM01":"1234567890000",
                     "CLM02":"177",
                     "ns0:C023":{
                        "C02301":"81",
                        "C02302":"B",
                        "C02303":"1"
                     },
                     "CLM06":"Y",
                     "CLM07":"A",
                     "CLM08":"Y",
                     "CLM09":"Y"
                  },
                  "ns0:REF_4":[
                     {
                        "REF01":"D9",
                        "REF02":"12812-2145488995"
                     },
                     {
                        "REF01":"EA",
                        "REF02":"760690339"
                     }
                  ],
                  "ns0:NTE":{
                     "NTE01":"ADD",
                     "NTE02":"LC0 AC102"
                  },
                  "ns0:HI":{
                     "ns0:C022":{
                        "C02201":"ABK",
                        "C02202":"Z01812"
                     },
                     "ns0:C022_2":{
                        "C02201":"ABF",
                        "C02202":"Z20822"
                     }
                  },
                  "ns0:NM1Loop3":{
                     "ns0:NM1_3":{
                        "NM101":"DN",
                        "NM102":"1",
                        "NM103":"JONH",
                        "NM104":"SMITH",
                        "NM107":"JR",
                        "NM108":"XX",
                        "NM109":"1234567891"
                     }
                  },
                  "ns0:LXLoop1":[
                     {
                        "ns0:LX":{
                           "LX01":"1"
                        },
                        "ns0:SV1":{
                           "ns0:C003":{
                              "C00301":"HC",
                              "C00302":"U0005"
                           },
                           "SV102":"25",
                           "SV103":"UN",
                           "SV104":"1",
                           "ns0:C004":{
                              "C00401":"1",
                              "C00402":"2"
                           }
                        },
                        "ns0:DTP_4":{
                           "DTP01":"472",
                           "DTP02":"D8",
                           "DTP03":"20211018"
                        },
                        "ns0:REF_7":{
                           "REF01":"6R",
                           "REF02":"1234567890000-1"
                        }
                     },
                     {
                        "ns0:LX":{
                           "LX01":"2"
                        },
                        "ns0:SV1":{
                           "ns0:C003":{
                              "C00301":"HC",
                              "C00302":"U0003"
                           },
                           "SV102":"152",
                           "SV103":"UN",
                           "SV104":"1",
                           "ns0:C004":{
                              "C00401":"1",
                              "C00402":"2"
                           }
                        },
                        "ns0:DTP_4":{
                           "DTP01":"472",
                           "DTP02":"D8",
                           "DTP03":"20211018"
                        },
                        "ns0:REF_7":{
                           "REF01":"6R",
                           "REF02":"1234567890000-2"
                        }
                     }
                  ]
               }
            },
            {
               "ns0:HL":{
                  "HL01":"3",
                  "HL02":"1",
                  "HL03":"22",
                  "HL04":"0"
               },
               "ns0:SBR":{
                  "SBR01":"P",
                  "SBR02":"18",
                  "SBR03":"1234567MC08",
                  "SBR09":"BL"
               },
               "ns0:NM1Loop2":[
                  {
                     "ns0:NM1_2":{
                        "NM101":"IL",
                        "NM102":"1",
                        "NM103":"JOHN",
                        "NM104":"SMITH",
                        "NM105":"L",
                        "NM108":"MI",
                        "NM109":"FV12345678902"
                     },
                     "ns0:N3_2":{
                        "N301":"123 FAISON ST"
                     },
                     "ns0:N4_2":{
                        "N401":"EMPORIA",
                        "N402":"VA",
                        "N403":"238472623"
                     },
                     "ns0:DMG":{
                        "DMG01":"D8",
                        "DMG02":"19851019",
                        "DMG03":"M"
                     },
                     "ns0:REF_3":{
                        "REF01":"SY",
                        "REF02":"123456789"
                     }
                  },
                  {
                     "ns0:NM1_2":{
                        "NM101":"PR",
                        "NM102":"2",
                        "NM103":"VA BLUE CROSS OUT OF STATE",
                        "NM108":"PI",
                        "NM109":"999990070"
                     },
                     "ns0:N3_2":{
                        "N301":"PO BOX 27401"
                     },
                     "ns0:N4_2":{
                        "N401":"RICHMOND",
                        "N402":"VA",
                        "N403":"23279"
                     }
                  }
               ],
               "ns0:CLMLoop1":{
                  "ns0:CLM":{
                     "CLM01":"1234567890001",
                     "CLM02":"177",
                     "ns0:C023":{
                        "C02301":"81",
                        "C02302":"B",
                        "C02303":"1"
                     },
                     "CLM06":"Y",
                     "CLM07":"A",
                     "CLM08":"Y",
                     "CLM09":"Y"
                  },
                  "ns0:REF_4":[
                     {
                        "REF01":"D9",
                        "REF02":"12812-2145488952"
                     },
                     {
                        "REF01":"EA",
                        "REF02":"822003559"
                     }
                  ],
                  "ns0:NTE":{
                     "NTE01":"ADD",
                     "NTE02":"LC0 AC102"
                  },
                  "ns0:HI":{
                     "ns0:C022":{
                        "C02201":"ABK",
                        "C02202":"Z01812"
                     },
                     "ns0:C022_2":{
                        "C02201":"ABF",
                        "C02202":"Z20822"
                     }
                  },
                  "ns0:NM1Loop3":{
                     "ns0:NM1_3":{
                        "NM101":"DN",
                        "NM102":"1",
                        "NM103":"JOHN",
                        "NM104":"SMITH",
                        "NM107":"JR",
                        "NM108":"XX",
                        "NM109":"1234567891"
                     }
                  },
                  "ns0:LXLoop1":[
                     {
                        "ns0:LX":{
                           "LX01":"1"
                        },
                        "ns0:SV1":{
                           "ns0:C003":{
                              "C00301":"HC",
                              "C00302":"U0005"
                           },
                           "SV102":"25",
                           "SV103":"UN",
                           "SV104":"1",
                           "ns0:C004":{
                              "C00401":"1",
                              "C00402":"2"
                           }
                        },
                        "ns0:DTP_4":{
                           "DTP01":"472",
                           "DTP02":"D8",
                           "DTP03":"20211018"
                        },
                        "ns0:REF_7":{
                           "REF01":"6R",
                           "REF02":"1234567890001-1"
                        }
                     },
                     {
                        "ns0:LX":{
                           "LX01":"2"
                        },
                        "ns0:SV1":{
                           "ns0:C003":{
                              "C00301":"HC",
                              "C00302":"U0003"
                           },
                           "SV102":"152",
                           "SV103":"UN",
                           "SV104":"1",
                           "ns0:C004":{
                              "C00401":"1",
                              "C00402":"2"
                           }
                        },
                        "ns0:DTP_4":{
                           "DTP01":"472",
                           "DTP02":"D8",
                           "DTP03":"20211018"
                        },
                        "ns0:REF_7":{
                           "REF01":"6R",
                           "REF02":"1234567890001-2"
                        }
                     }
                  ]
               }
            },
            {
               "ns0:HL":{
                  "HL01":"4",
                  "HL03":"20",
                  "HL04":"1"
               },
               "ns0:PRV":{
                  "PRV01":"BI",
                  "PRV02":"PXC",
                  "PRV03":"261QR0200X"
               },
               "ns0:NM1Loop2":[
                  {
                     "ns0:NM1_2":{
                        "NM101":"85",
                        "NM102":"2",
                        "NM103":"ST MARYS HOSPITAL",
                        "NM108":"XX",
                        "NM109":"1316015985"
                     },
                     "ns0:N3_2":{
                        "N301":"5801 BREMO ROAD"
                     },
                     "ns0:N4_2":{
                        "N401":"RICHMOND",
                        "N402":"VA",
                        "N403":"232261907"
                     },
                     "ns0:REF_3":{
                        "REF01":"EI",
                        "REF02":"205886018"
                     },
                     "ns0:PER_2":{
                        "PER01":"IC",
                        "PER02":"ABC DEF",
                        "PER03":"TE",
                        "PER04":"1234567890"
                     }
                  },
                  {
                     "ns0:NM1_2":{
                        "NM101":"87",
                        "NM102":"2"
                     },
                     "ns0:N3_2":{
                        "N301":"PO BOX 100767"
                     },
                     "ns0:N4_2":{
                        "N401":"ATLANTA",
                        "N402":"GA",
                        "N403":"303840767"
                     }
                  }
               ]
            },
            {
               "ns0:HL":{
                  "HL01":"5",
                  "HL02":"4",
                  "HL03":"22",
                  "HL04":"0"
               },
               "ns0:SBR":{
                  "SBR01":"P",
                  "SBR02":"18",
                  "SBR09":"MB"
               },
               "ns0:NM1Loop2":[
                  {
                     "ns0:NM1_2":{
                        "NM101":"IL",
                        "NM102":"1",
                        "NM103":"JOHN",
                        "NM104":"SMITH",
                        "NM108":"MI",
                        "NM109":"FV123456789"
                     },
                     "ns0:N3_2":{
                        "N301":"1234 DUMMY AVE"
                     },
                     "ns0:N4_2":{
                        "N401":"RICHMOND",
                        "N402":"VA",
                        "N403":"23226"
                     },
                     "ns0:DMG":{
                        "DMG01":"D8",
                        "DMG02":"19750918",
                        "DMG03":"M"
                     }
                  },
                  {
                     "ns0:NM1_2":{
                        "NM101":"PR",
                        "NM102":"2",
                        "NM103":"VA MEDICARE PART A  B",
                        "NM108":"PI",
                        "NM109":"999990071"
                     },
                     "ns0:N3_2":{
                        "N301":"PO BOX 100238"
                     },
                     "ns0:N4_2":{
                        "N401":"COLUMBIA",
                        "N402":"SC",
                        "N403":"29202"
                     }
                  }
               ],
               "ns0:CLMLoop1":{
                  "ns0:CLM":{
                     "CLM01":"FV12345678903",
                     "CLM02":"834",
                     "ns0:C023":{
                        "C02301":"11",
                        "C02302":"B",
                        "C02303":"1"
                     },
                     "CLM06":"Y",
                     "CLM07":"A",
                     "CLM08":"Y",
                     "CLM09":"Y"
                  },
                  "ns0:REF_4":[
                     {
                        "REF01":"D9",
                        "REF02":"12812-2145488939"
                     },
                     {
                        "REF01":"EA",
                        "REF02":"760355251"
                     }
                  ],
                  "ns0:NTE":{
                     "NTE01":"ADD",
                     "NTE02":"LC0 AC120"
                  },
                  "ns0:HI":{
                     "ns0:C022":{
                        "C02201":"ABK",
                        "C02202":"M25551"
                     }
                  },
                  "ns0:NM1Loop3":[
                     {
                        "ns0:NM1_3":{
                           "NM101":"DN",
                           "NM102":"1",
                           "NM103":"BAGGESEN",
                           "NM104":"J",
                           "NM105":"RAND",
                           "NM108":"XX",
                           "NM109":"1417932641"
                        }
                     },
                     {
                        "ns0:NM1_3":{
                           "NM101":"77",
                           "NM102":"2",
                           "NM103":"BON SECOURS IMAGING CENTER REYNOLDS CROSSING"
                        },
                        "ns0:N3_3":{
                           "N301":"6605 W BROAD ST"
                        },
                        "ns0:N4_3":{
                           "N401":"RICHMOND",
                           "N402":"VA",
                           "N403":"232301714"
                        }
                     }
                  ],
                  "ns0:SBRLoop1":{
                     "ns0:SBR_2":{
                        "SBR01":"S",
                        "SBR02":"18",
                        "SBR03":"VASU12345",
                        "SBR09":"BL"
                     },
                     "ns0:OI":{
                        "OI03":"Y",
                        "OI06":"Y"
                     },
                     "ns0:NM1Loop4":[
                        {
                           "ns0:NM1_4":{
                              "NM101":"IL",
                              "NM102":"1",
                              "NM103":"JOHN",
                              "NM104":"SMITH",
                              "NM108":"MI",
                              "NM109":"FV12345678905"
                           },
                           "ns0:N3_4":{
                              "N301":"5141 LIBBIE AVE"
                           },
                           "ns0:N4_4":{
                              "N401":"RICHMOND",
                              "N402":"VA",
                              "N403":"23226"
                           }
                        },
                        {
                           "ns0:NM1_4":{
                              "NM101":"PR",
                              "NM102":"2",
                              "NM103":"VA BLUE CROSS SUPPLEMENT MEDICARE",
                              "NM108":"PI",
                              "NM109":"999990070"
                           },
                           "ns0:N3_4":{
                              "N301":"P O BOX 27401"
                           },
                           "ns0:N4_4":{
                              "N401":"RICHMOND",
                              "N402":"VA",
                              "N403":"23279"
                           }
                        }
                     ]
                  },
                  "ns0:LXLoop1":{
                     "ns0:LX":{
                        "LX01":"1"
                     },
                     "ns0:SV1":{
                        "ns0:C003":{
                           "C00301":"HC",
                           "C00302":"73502",
                           "C00303":"TC",
                           "C00304":"RT"
                        },
                        "SV102":"834",
                        "SV103":"UN",
                        "SV104":"1",
                        "ns0:C004":{
                           "C00401":"1"
                        }
                     },
                     "ns0:DTP_4":{
                        "DTP01":"472",
                        "DTP02":"D8",
                        "DTP03":"20211019"
                     },
                     "ns0:REF_7":{
                        "REF01":"6R",
                        "REF02":"FV12345678903-1"
                     }
                  }
               }
            }
         ],
         "SE":{
            "SE01":"104",
            "SE02":"72278993"
         }
      }
   }
]